name = "try1"
uuid = "ec28a684-da67-4ae7-bc3b-e459b5799d37"
authors = ["Dongge Jia"]
version = "1.0.0-DEV"

[deps]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"

[compat]
julia = "1.8.5"
Example = "0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
